openapi: 3.0.0
info:
  title: Auth API
  version: "1.0.0"
  description: User registration, login and list API

paths:
  /users/register:
    $ref: "./swagger/users/register.yml"
  /users/login:
    $ref: "./swagger/users/login.yml"
  /users:
    $ref: "./swagger/users/list.yml"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
